name: Rust CI/CD

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_push:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_AUTH_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_AUTH_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Login to Azure container registry
        run: |
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Get version from github ref
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/joel-bot:${{ steps.get_version.outputs.VERSION }}

      - name: Azure container registry logout
        if: always()
        run: |
          docker logout ${{ secrets.AZURE_CONTAINER_REGISTRY }}

  deploy:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    needs:
      - build_and_push

    steps:
      - uses: actions/checkout@v5

      - name: Get version from github ref
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Get last committer
        id: last_committer
        run: echo "committer=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_OUTPUT

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_AUTH_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_AUTH_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy joel-bot Azure environment
        uses: azure/bicep-deploy@v2
        with:
          operation: create
          type: deploymentStack
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          location: swedencentral
          name: joel-bot-prod
          template-file: ./infrastructure/main.bicep
          action-on-unmanage-resources: delete
          deny-settings-mode: none
          parameters: |
            {
              "addressPrefix": "${{ vars.AZURE_ADDRESS_PREFIX }}",
              "environment": "prod",
              "imageVersion": "${{ steps.get_version.outputs.VERSION }}",
              "tags": {
                "lastUpdatedBy": "${{ steps.last_committer.outputs.committer }}",
                "version": "${{ steps.get_version.outputs.VERSION }}"
              }
            }
